### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by RayhanTabase** [topeogunleye/conference-page#3]
Everything looks great but I think centering the hamburger menu vertically in the mobile version will make it look more awesome

**Comment by ShadyShawkat** [comment]
Hi @topeogunleye,

Your project looks great but I have some suggestions: 

- [x] Your `README.md` file has the wrong project name displayed. 
- [x] I think the more button on your home page on the desktop view is too wide. You can set a `max-width` on it so it doesn't look so wide on wide screens.

Other than that, your project looks complete. 👍🏻

**Comment by topeogunleye** [comment]
Hey @ShadyShawkat @RayhanTabase, thank you for taking the time to check out my project. 🙏🏻
I'll definitely consider your feedback.
